-- Phase 1a: Add enum values ONLY (must commit before using them)

ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PENDING_PAYMENT';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PROCESSING';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'RETURN_REQUESTED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'RETURN_APPROVED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'RETURNING';

ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'REFUND_REQUIRED';
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'REFUND_PENDING';
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'COD_COLLECTED';

ALTER TYPE "RefundStatus" ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE "RefundStatus" ADD VALUE IF NOT EXISTS 'FAILED';
ALTER TYPE "RefundStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

ALTER TYPE "ShipmentStatus" ADD VALUE IF NOT EXISTS 'READY_TO_PICK';
ALTER TYPE "ShipmentStatus" ADD VALUE IF NOT EXISTS 'SHIPPING';
ALTER TYPE "ShipmentStatus" ADD VALUE IF NOT EXISTS 'FAILED';

-- Create new enum types
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'WebhookEventStatus') THEN
    CREATE TYPE "WebhookEventStatus" AS ENUM (
      'RECEIVED',
      'PROCESSING',
      'PROCESSED',
      'FAILED_RETRYABLE',
      'FAILED_DEAD',
      'IGNORED_DUPLICATE'
    );
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'OutboxEventStatus') THEN
    CREATE TYPE "OutboxEventStatus" AS ENUM (
      'PENDING',
      'PROCESSING',
      'PROCESSED',
      'FAILED_RETRYABLE',
      'FAILED_DEAD'
    );
  END IF;
END $$;
