ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'CREATED';
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';
ALTER TYPE "ShipmentStatus" ADD VALUE IF NOT EXISTS 'UNKNOWN';

ALTER TABLE "orders" ALTER COLUMN "status" SET DEFAULT 'CREATED';
