export const OUTBOX_QUEUE = 'outbox';

export const OUTBOX_EVENT_TYPE = {
  SHIPMENT_CREATE_REQUESTED: 'SHIPMENT_CREATE_REQUESTED',
  SHIPMENT_CANCEL_REQUESTED: 'SHIPMENT_CANCEL_REQUESTED',
  REFUND_CREATE_REQUESTED: 'REFUND_CREATE_REQUESTED',
  PAYMENT_POST_SUCCESS: 'PAYMENT_POST_SUCCESS',
} as const;

export type OutboxEventType = (typeof OUTBOX_EVENT_TYPE)[keyof typeof OUTBOX_EVENT_TYPE];
